2025-05-07 12:07:02,826 - engineio.client - ERROR - requests package is not installed -- cannot send HTTP requests!-_connect_polling
2025-05-07 12:07:57,734 - engineio.client - ERROR - requests package is not installed -- cannot send HTTP requests!-_connect_polling
2025-05-07 14:20:16,692 - engineio.client - ERROR - requests package is not installed -- cannot send HTTP requests!-_connect_polling
2025-05-07 14:21:05,969 - engineio.client - ERROR - requests package is not installed -- cannot send HTTP requests!-_connect_polling
2025-05-07 14:21:50,329 - engineio.client - ERROR - requests package is not installed -- cannot send HTTP requests!-_connect_polling
2025-05-07 14:28:27,768 - engineio.client - ERROR - requests package is not installed -- cannot send HTTP requests!-_connect_polling
2025-05-07 14:30:48,744 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:05:26,903 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:06:37,516 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:07:39,576 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:08:30,272 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:18:20,411 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:19:23,176 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:20:37,342 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:21:35,028 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:43:02,302 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:45:36,802 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:46:49,203 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 15:59:32,420 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:10:58,461 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:19:20,845 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:33:48,578 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:45:00,452 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:49:50,673 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:50:36,128 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:50:43,824 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:53:02,515 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:58:35,649 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 16:59:37,581 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 17:02:15,473 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 17:05:50,057 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 17:07:44,518 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 17:10:44,791 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 17:12:17,122 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 17:15:35,177 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 17:20:59,863 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-07 17:50:08,383 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-10 17:00:58,578 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-10 17:02:07,947 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-10 17:02:09,497 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-10 17:02:10,774 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-10 17:05:01,466 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-10 17:58:26,228 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-10 20:24:49,725 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-10 21:39:31,719 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 13:45:57,640 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 13:46:00,594 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 13:46:01,893 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 13:46:03,582 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 13:49:16,359 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:07:30,755 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:10:36,361 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:11:36,778 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:12:46,306 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:15:52,518 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:18:41,976 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:19:41,462 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:20:31,149 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:21:30,912 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:25:05,042 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:33:03,932 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:42:13,401 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:45:18,565 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:45:44,535 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:45:47,074 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:45:49,081 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:45:50,583 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:45:52,587 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:52:29,382 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:54:11,227 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 14:59:23,209 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 15:00:05,897 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 15:21:39,067 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 17:26:28,521 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 17:26:54,913 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 17:37:37,194 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 17:44:14,292 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-12 17:44:32,754 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-13 13:58:28,066 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-13 14:01:57,240 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-13 14:23:55,814 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-13 14:23:58,455 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-13 14:31:43,246 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-13 14:32:20,510 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-13 14:34:56,958 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-13 14:41:10,935 - engineio.client - ERROR - websocket-client package not installed, only polling transport is available-_connect_websocket
2025-05-15 00:22:34,086 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:119> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1318a0e50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.398 seconds-_run_once
2025-05-15 00:29:21,391 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:117> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13207fe90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.196 seconds-_run_once
2025-05-15 00:42:27,799 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:98> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(13, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x133f1b750>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.531 seconds-_run_once
2025-05-15 00:50:23,119 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:114> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1214b77d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.144 seconds-_run_once
2025-05-15 00:50:23,135 - asyncio - WARNING - Executing <Task pending name='Task-3' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:114> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x12147fbd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.169 seconds-_run_once
2025-05-15 00:50:23,150 - asyncio - WARNING - Executing <Task pending name='Task-5' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:114> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x12149ab10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.165 seconds-_run_once
2025-05-15 00:50:23,155 - asyncio - WARNING - Executing <Task pending name='Task-11' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:114> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1214b7390>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.166 seconds-_run_once
2025-05-15 00:50:23,162 - asyncio - WARNING - Executing <Task pending name='Task-9' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:114> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1214b7e10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.145 seconds-_run_once
2025-05-15 00:50:23,163 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:114> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1214b76d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.128 seconds-_run_once
2025-05-15 09:50:14,234 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:105> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(16, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x13f89ea50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.172 seconds-_run_once
2025-05-15 09:58:08,678 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:105> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(16, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x11ec6b690>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.175 seconds-_run_once
2025-05-15 10:14:16,685 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11bdc5b50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.202 seconds-_run_once
2025-05-15 10:34:37,325 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cb96350>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.208 seconds-_run_once
2025-05-15 10:34:37,447 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cb96810>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.108 seconds-_run_once
2025-05-15 10:34:44,686 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cb74150>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.117 seconds-_run_once
2025-05-15 10:34:48,960 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cba1090>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.104 seconds-_run_once
2025-05-15 10:34:49,115 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cba1890>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.141 seconds-_run_once
2025-05-15 10:34:50,323 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cba72d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.136 seconds-_run_once
2025-05-15 10:34:54,249 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cb66310>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.136 seconds-_run_once
2025-05-15 10:34:56,720 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cb8f6d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.125 seconds-_run_once
2025-05-15 10:34:57,603 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cba7a50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.272 seconds-_run_once
2025-05-15 10:34:57,760 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cba7250>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.151 seconds-_run_once
2025-05-15 10:34:58,122 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cba3710>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.230 seconds-_run_once
2025-05-15 10:35:00,345 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cbac310>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.155 seconds-_run_once
2025-05-15 10:35:01,118 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cbae310>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.173 seconds-_run_once
2025-05-15 10:35:02,107 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cbacf90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.939 seconds-_run_once
2025-05-15 10:35:03,039 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cbaed90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.925 seconds-_run_once
2025-05-15 10:35:03,296 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cbb01d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.239 seconds-_run_once
2025-05-15 10:35:08,003 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cbac390>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.103 seconds-_run_once
2025-05-15 10:35:12,193 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cb6e890>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.117 seconds-_run_once
2025-05-15 10:35:17,401 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cbaef10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.124 seconds-_run_once
2025-05-15 10:35:50,768 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cb8cd50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.598 seconds-_run_once
2025-05-15 10:36:34,348 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cc7e590>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.141 seconds-_run_once
2025-05-15 10:36:34,566 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cc7e790>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.211 seconds-_run_once
2025-05-15 10:36:36,513 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11cc6bb50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.538 seconds-_run_once
2025-05-15 10:43:01,280 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b1750>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.126 seconds-_run_once
2025-05-15 10:43:01,397 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b5750>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.111 seconds-_run_once
2025-05-15 10:43:01,656 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b10d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.153 seconds-_run_once
2025-05-15 10:43:02,532 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b53d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.154 seconds-_run_once
2025-05-15 10:43:02,667 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b5310>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.127 seconds-_run_once
2025-05-15 10:43:02,808 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b5810>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.137 seconds-_run_once
2025-05-15 10:43:02,950 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b5950>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.136 seconds-_run_once
2025-05-15 10:43:03,064 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b5b10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.106 seconds-_run_once
2025-05-15 10:43:03,620 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b5f50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.187 seconds-_run_once
2025-05-15 10:43:03,744 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b5fd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.119 seconds-_run_once
2025-05-15 10:43:03,893 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6ba110>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.142 seconds-_run_once
2025-05-15 10:43:04,140 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6ba450>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.243 seconds-_run_once
2025-05-15 10:43:04,469 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b12d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.325 seconds-_run_once
2025-05-15 10:43:04,934 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b18d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.118 seconds-_run_once
2025-05-15 10:43:05,079 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b08d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.139 seconds-_run_once
2025-05-15 10:43:05,225 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b0590>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.138 seconds-_run_once
2025-05-15 10:43:05,402 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b0150>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.172 seconds-_run_once
2025-05-15 10:43:05,649 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13ea06ed0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.244 seconds-_run_once
2025-05-15 10:43:05,778 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b0fd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.125 seconds-_run_once
2025-05-15 10:43:06,400 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13ea321d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.131 seconds-_run_once
2025-05-15 10:43:06,644 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b0fd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.125 seconds-_run_once
2025-05-15 10:43:07,378 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b0f50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.187 seconds-_run_once
2025-05-15 10:43:07,520 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b0cd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.131 seconds-_run_once
2025-05-15 10:43:07,631 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6b0b90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.109 seconds-_run_once
2025-05-15 10:43:08,387 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6bad50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.121 seconds-_run_once
2025-05-15 10:43:09,706 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e6baf10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.116 seconds-_run_once
2025-05-15 10:43:10,662 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11f0ce9d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.178 seconds-_run_once
2025-05-15 10:43:10,819 - asyncio - WARNING - Executing <Task pending name='Task-7' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e687450>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.152 seconds-_run_once
2025-05-15 10:55:53,501 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13bab8a90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.104 seconds-_run_once
2025-05-15 10:56:49,467 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303a1e90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.234 seconds-_run_once
2025-05-15 10:56:49,570 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303b8750>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.101 seconds-_run_once
2025-05-15 10:56:50,023 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303c0550>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.129 seconds-_run_once
2025-05-15 10:56:50,170 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303b4ad0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.147 seconds-_run_once
2025-05-15 10:56:50,324 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303b45d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.153 seconds-_run_once
2025-05-15 10:56:50,569 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303bfc10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.245 seconds-_run_once
2025-05-15 10:56:52,602 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x130392110>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.103 seconds-_run_once
2025-05-15 10:56:53,559 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303b4f50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.110 seconds-_run_once
2025-05-15 10:56:54,553 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303be7d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.106 seconds-_run_once
2025-05-15 10:56:57,941 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303b87d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.101 seconds-_run_once
2025-05-15 10:57:00,065 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ec25350>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.100 seconds-_run_once
2025-05-15 10:57:01,549 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ec2d790>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.102 seconds-_run_once
2025-05-15 10:57:03,914 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ec2bb50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.112 seconds-_run_once
2025-05-15 10:57:08,485 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ec26290>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.105 seconds-_run_once
2025-05-15 10:57:11,041 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13e7d8b10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.200 seconds-_run_once
2025-05-15 10:57:11,238 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13e7d4950>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.196 seconds-_run_once
2025-05-15 10:57:11,424 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13e7cddd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.186 seconds-_run_once
2025-05-15 10:57:12,024 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ec37c90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.121 seconds-_run_once
2025-05-15 10:57:12,233 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ec378d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.100 seconds-_run_once
2025-05-15 10:57:12,359 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13038c790>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.101 seconds-_run_once
2025-05-15 10:57:12,989 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1303b8b50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.120 seconds-_run_once
2025-05-15 11:08:32,939 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e9a8910>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.102 seconds-_run_once
2025-05-15 11:12:31,366 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b354b90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.299 seconds-_run_once
2025-05-15 11:12:31,828 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ebf0f10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.458 seconds-_run_once
2025-05-15 11:12:32,640 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b389390>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.809 seconds-_run_once
2025-05-15 11:12:33,508 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b3897d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.864 seconds-_run_once
2025-05-15 11:12:35,087 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b389f50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 1.568 seconds-_run_once
2025-05-15 11:12:36,491 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b38cd90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 1.384 seconds-_run_once
2025-05-15 11:12:38,643 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b38ebd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 2.150 seconds-_run_once
2025-05-15 11:12:42,771 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b389a10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 4.127 seconds-_run_once
2025-05-15 11:12:49,087 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b3953d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 6.308 seconds-_run_once
2025-05-15 11:13:00,257 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b39ff50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 11.144 seconds-_run_once
2025-05-15 11:13:05,178 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b3a9fd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 4.913 seconds-_run_once
2025-05-15 11:13:05,958 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b3a5390>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.779 seconds-_run_once
2025-05-15 11:13:06,104 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b3b2910>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.145 seconds-_run_once
2025-05-15 11:13:28,432 - asyncio - WARNING - Executing <Task pending name='Task-13' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13b3cb7d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.112 seconds-_run_once
2025-05-15 11:19:35,232 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1203447d0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.157 seconds-_run_once
2025-05-15 11:21:32,643 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x133984290>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.101 seconds-_run_once
2025-05-15 11:27:48,283 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e166ad0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.339 seconds-_run_once
2025-05-15 16:43:10,494 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:105> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(16, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x120c07910>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.216 seconds-_run_once
2025-05-15 17:28:15,781 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:105> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(16, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x11ca29850>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.199 seconds-_run_once
2025-05-16 16:54:44,844 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:105> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(18, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x13321af90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.178 seconds-_run_once
2025-05-17 17:00:39,041 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:105> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(16, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x14044bdd0>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.187 seconds-_run_once
2025-05-17 20:46:58,072 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(16, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x13b6aab90>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.124 seconds-_run_once
2025-05-18 08:52:15,589 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x13c754990>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.139 seconds-_run_once
2025-05-19 09:50:55,848 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:105> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(16, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x11e388b10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.206 seconds-_run_once
2025-05-19 10:28:37,326 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e728e10>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.101 seconds-_run_once
2025-05-19 10:33:31,132 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11e93d790>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.116 seconds-_run_once
2025-05-19 10:34:52,701 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11eaa9d50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.152 seconds-_run_once
2025-05-19 10:35:08,054 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ecc6850>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.102 seconds-_run_once
2025-05-19 10:35:13,237 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ecca790>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.141 seconds-_run_once
2025-05-19 10:35:18,368 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ece1790>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.104 seconds-_run_once
2025-05-19 10:35:23,506 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ebbfd50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.101 seconds-_run_once
2025-05-19 10:35:28,633 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11ebcf710>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.101 seconds-_run_once
2025-05-19 14:06:41,737 - asyncio - WARNING - Executing <Task pending name='Task-1' coro=<Remote.connect_ws() running at /Users/zhao/Desktop/git/qmt-remote-auto-order/api/remote.py:105> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(16, handle=<Handle BaseS...events.py:291>)(), <TaskWakeupMethWrapper object at 0x13344cc50>()] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:184] created at /Users/zhao/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py:626> took 0.168 seconds-_run_once
